spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    forward-headers-strategy: framework

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

app:
  cookie:
    domain: ${APP_COOKIE_DOMAIN}
    max-age: ${APP_COOKIE_MAX_AGE:604800}
    secure: ${APP_COOKIE_SECURE:true}

